import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { SCREENSHOT_PAGES } from './pages';
import { SCREENSHOTS_DIR } from './screenshots-dir';

// Regenerates docs/screenshots/README.md from pages.ts, listing every page that has a PNG.
export default function globalTeardown(): void {
  if (!existsSync(SCREENSHOTS_DIR)) {
    return;
  }

  const sections = SCREENSHOT_PAGES.filter((entry) =>
    existsSync(join(SCREENSHOTS_DIR, `${entry.name}.png`)),
  ).map((entry) =>
    [`## ${entry.title}`, '', entry.description, '', `![${entry.title}](${entry.name}.png)`].join(
      '\n',
    ),
  );

  const readme = [
    '# Screenshots',
    '',
    '<!-- Generated by `task docs:screenshots` (src/frontend/buddy/screenshots). Do not edit by hand:',
    '     change the titles and descriptions in screenshots/pages.ts instead. -->',
    '',
    'Every page of Buddy, signed in as the demo guardian Sara Holm or her son Emil. The data is a',
    'demo family seeded fresh for each run, so dates are relative to the day the screenshots were',
    'taken.',
    '',
    ...sections.flatMap((section) => [section, '']),
  ].join('\n');

  writeFileSync(join(SCREENSHOTS_DIR, 'README.md'), readme);
}
