@buddy_HostAddress = http://localhost:5193
@keycloak_HostAddress = http://keycloak:8080
@keycloak_realm = buddy
@keycloak_client_id = buddy-api
@keycloak_username = kim.ipsen
@keycloak_password = starspy

GET {{buddy_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{buddy_HostAddress}}/openapi/users.json
Accept: application/json

###

# @name login
POST {{keycloak_HostAddress}}/realms/{{keycloak_realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{keycloak_client_id}}&grant_type=password&username={{keycloak_username}}&password={{keycloak_password}}

###

GET {{buddy_HostAddress}}/users/me
Authorization: Bearer {{login.response.body.$.access_token}}
Accept: application/json

###

GET {{buddy_HostAddress}}/users/me/events
Authorization: Bearer {{login.response.body.$.access_token}}
Accept: application/json

###

GET {{buddy_HostAddress}}/users/me/events?pageSize=1&cursor=AQAAAAAAAAA=
Authorization: Bearer {{login.response.body.$.access_token}}
Accept: application/json

###

PATCH {{buddy_HostAddress}}/users/me/name
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json
Accept: application/json

{
  "givenName": "Kim",
  "familyName": "Ipsen"
}

###

PATCH {{buddy_HostAddress}}/users/me/email
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json
Accept: application/json

{
  "email": "kim.ipsen@knowit.dk"
}

###

POST {{buddy_HostAddress}}/users/me/email/verify/resend
Authorization: Bearer {{login.response.body.$.access_token}}

###

# Token comes from the LoggingEmailSender's log output until a real provider is wired in.
POST {{buddy_HostAddress}}/users/me/email/verify
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json
Accept: application/json

{
  "token": "REPLACE_WITH_TOKEN_FROM_LOG"
}

###

DELETE {{buddy_HostAddress}}/users/me
Authorization: Bearer {{login.response.body.$.access_token}}

